
install:
  - pip install pytest-cov
  - pip install imageio
  - pip install -r requirements.txt
  - pip install -e .

language: python
cache: pip
python:
  - 3.6
  - 3.5
  - 3.4

branches:
  only:
    - master

script:
  - pytest
